version: '3'
services:
  postgres:
    image: postgres-venkat
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped

#  application:
#    depends_on:
#      - postgres
#    ports:
#    - "8080:8080"
#    image: tedtalks-venkat
#    hostname: Venkat
#    oom_kill_disable: true
volumes:
  postgres-data: